export const config = {
  github: {
    username: "enbeec",
  },
  about: {
    name: "Val Currie",
    bio: `from Nashville, TN -- Duis duis pariatur dolor esse ex incididunt proident culpa. Ea reprehenderit esse non amet excepteur culpa veniam incididunt. Consectetur velit ex occaecat reprehenderit excepteur ipsum labore minim commodo ad cillum cillum commodo esse. Fugiat id elit excepteur dolore pariatur cillum officia. Ipsum laborum laborum proident enim Lorem eiusmod sint eu sint. Tempor occaecat Lorem ad consectetur esse consectetur velit. Dolore consequat labore proident veniam nostrud cillum consequat excepteur. Consectetur excepteur culpa ex dolore. Fugiat proident qui eiusmod enim mollit quis ex officia sit ea cillum anim minim. Ut officia incididunt proident adipisicing eu eiusmod occaecat ea. Voluptate sunt est excepteur amet incididunt tempor voluptate incididunt dolor dolor. Eiusmod mollit mollit duis magna ipsum culpa ut ullamco tempor aute do voluptate occaecat. Ullamco eiusmod duis nostrud duis est est est do quis officia dolore cupidatat. Pariatur ad ad commodo nulla elit ipsum elit reprehenderit. Nostrud sunt est labore reprehenderit ipsum. Ex ipsum sit labore pariatur amet et aliquip aliquip est. Culpa reprehenderit occaecat sint voluptate officia non in. Ea officia consectetur officia mollit incididunt officia ea in exercitation aliquip velit deserunt esse. Ut eu cillum dolor velit laborum sit dolore nisi sunt. Excepteur anim veniam excepteur do in id. Elit reprehenderit ut laboris aliquip reprehenderit sint excepteur deserunt anim eu ullamco laboris. Consectetur magna magna officia enim anim pariatur consectetur nulla. Reprehenderit reprehenderit fugiat sint ex fugiat in excepteur ea velit nisi. Mollit minim nisi laboris commodo ex ex. Sunt cillum ut velit dolore exercitation dolore nulla Lorem. Non labore veniam non nulla magna fugiat. Sunt enim irure exercitation tempor eiusmod aliquip officia occaecat ea. Ad incididunt culpa nostrud aliquip nisi tempor proident ad duis. Amet aliqua Lorem ad voluptate do minim.`,
    handle: "valcuri",
  },
};
